// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJIlI4HovqzYxFBDJh-ZmJdlJd4YIGjtI',
    appId: '1:962206934954:web:44ab335056f8b2702cedd3',
    messagingSenderId: '962206934954',
    projectId: 'chatapp-hab',
    authDomain: 'chatapp-hab.firebaseapp.com',
    storageBucket: 'chatapp-hab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOiV70tUDOs2jT2Xllo-zkVGjax5v_iaE',
    appId: '1:962206934954:android:0f6c9e429ae4ca1e2cedd3',
    messagingSenderId: '962206934954',
    projectId: 'chatapp-hab',
    storageBucket: 'chatapp-hab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWD88BmUBYIDfV0PD0Uqzg8_2R3wsOrzQ',
    appId: '1:962206934954:ios:0f1c94bbe49076e22cedd3',
    messagingSenderId: '962206934954',
    projectId: 'chatapp-hab',
    storageBucket: 'chatapp-hab.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWD88BmUBYIDfV0PD0Uqzg8_2R3wsOrzQ',
    appId: '1:962206934954:ios:0f1c94bbe49076e22cedd3',
    messagingSenderId: '962206934954',
    projectId: 'chatapp-hab',
    storageBucket: 'chatapp-hab.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJIlI4HovqzYxFBDJh-ZmJdlJd4YIGjtI',
    appId: '1:962206934954:web:ec230abdef75e79f2cedd3',
    messagingSenderId: '962206934954',
    projectId: 'chatapp-hab',
    authDomain: 'chatapp-hab.firebaseapp.com',
    storageBucket: 'chatapp-hab.firebasestorage.app',
  );
}
